# Generated by Django 4.2.4 on 2023-08-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('offerp', models.IntegerField()),
                ('image', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='KidBoys',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshopapp.product')),
                ('author', models.CharField(max_length=100)),
            ],
            bases=('myshopapp.product',),
        ),
        migrations.CreateModel(
            name='KidGawn',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshopapp.product')),
                ('author', models.CharField(max_length=100)),
            ],
            bases=('myshopapp.product',),
        ),
        migrations.CreateModel(
            name='KidSummer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshopapp.product')),
                ('author', models.CharField(max_length=100)),
            ],
            bases=('myshopapp.product',),
        ),
        migrations.CreateModel(
            name='MenJeans',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshopapp.product')),
                ('author', models.CharField(max_length=100)),
            ],
            bases=('myshopapp.product',),
        ),
        migrations.CreateModel(
            name='MenShirt',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshopapp.product')),
                ('author', models.CharField(max_length=100)),
            ],
            bases=('myshopapp.product',),
        ),
        migrations.CreateModel(
            name='MenTShirt',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshopapp.product')),
                ('author', models.CharField(max_length=100)),
            ],
            bases=('myshopapp.product',),
        ),
        migrations.CreateModel(
            name='WomenJeans',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshopapp.product')),
                ('author', models.CharField(max_length=100)),
            ],
            bases=('myshopapp.product',),
        ),
        migrations.CreateModel(
            name='WomenKurti',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshopapp.product')),
                ('author', models.CharField(max_length=100)),
            ],
            bases=('myshopapp.product',),
        ),
        migrations.CreateModel(
            name='WomenTop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshopapp.product')),
                ('author', models.CharField(max_length=100)),
            ],
            bases=('myshopapp.product',),
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopapp.register')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='myshopapp.OrderedItem', to='myshopapp.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopapp.register'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopapp.register')),
            ],
        ),
    ]
