# Generated by Django 4.2.4 on 2023-08-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopapp', '0002_order_product_kidboys_kidgawn_kidsummer_menjeans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
